/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserManagementRouteImport } from './routes/user-management'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as MasterDataRouteImport } from './routes/master-data'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ChildrenRouteImport } from './routes/children'
import { Route as CheckinRouteImport } from './routes/checkin'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as ActivitiesRouteImport } from './routes/activities'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PengaturanProfilRouteImport } from './routes/pengaturan.profil'
import { Route as PengaturanPenomoranRouteImport } from './routes/pengaturan.penomoran'
import { Route as PengaturanNotifikasiRouteImport } from './routes/pengaturan.notifikasi'
import { Route as PengaturanHariLiburRouteImport } from './routes/pengaturan.hari-libur'
import { Route as OperasionalInsidenRouteImport } from './routes/operasional.insiden'
import { Route as OperasionalCheckOutRouteImport } from './routes/operasional.check-out'
import { Route as OperasionalCheckInRouteImport } from './routes/operasional.check-in'
import { Route as OperasionalCatatanKesehatanRouteImport } from './routes/operasional.catatan-kesehatan'
import { Route as OperasionalBookingRouteImport } from './routes/operasional.booking'
import { Route as OperasionalAktivitasHarianRouteImport } from './routes/operasional.aktivitas-harian'
import { Route as MasterAnakRouteImport } from './routes/master.anak'
import { Route as MasterResourceRouteImport } from './routes/master.$resource'
import { Route as MasterDataResourceRouteImport } from './routes/master-data.$resource'
import { Route as LaporanReportRouteImport } from './routes/laporan.$report'
import { Route as KomunikasiPengumumanRouteImport } from './routes/komunikasi.pengumuman'
import { Route as KeuanganTagihanRouteImport } from './routes/keuangan.tagihan'
import { Route as KeuanganPembelianPaketRouteImport } from './routes/keuangan.pembelian-paket'
import { Route as KeuanganPembayaranRouteImport } from './routes/keuangan.pembayaran'

const UserManagementRoute = UserManagementRouteImport.update({
  id: '/user-management',
  path: '/user-management',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterDataRoute = MasterDataRouteImport.update({
  id: '/master-data',
  path: '/master-data',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChildrenRoute = ChildrenRouteImport.update({
  id: '/children',
  path: '/children',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckinRoute = CheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesRoute = ActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PengaturanProfilRoute = PengaturanProfilRouteImport.update({
  id: '/pengaturan/profil',
  path: '/pengaturan/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const PengaturanPenomoranRoute = PengaturanPenomoranRouteImport.update({
  id: '/pengaturan/penomoran',
  path: '/pengaturan/penomoran',
  getParentRoute: () => rootRouteImport,
} as any)
const PengaturanNotifikasiRoute = PengaturanNotifikasiRouteImport.update({
  id: '/pengaturan/notifikasi',
  path: '/pengaturan/notifikasi',
  getParentRoute: () => rootRouteImport,
} as any)
const PengaturanHariLiburRoute = PengaturanHariLiburRouteImport.update({
  id: '/pengaturan/hari-libur',
  path: '/pengaturan/hari-libur',
  getParentRoute: () => rootRouteImport,
} as any)
const OperasionalInsidenRoute = OperasionalInsidenRouteImport.update({
  id: '/operasional/insiden',
  path: '/operasional/insiden',
  getParentRoute: () => rootRouteImport,
} as any)
const OperasionalCheckOutRoute = OperasionalCheckOutRouteImport.update({
  id: '/operasional/check-out',
  path: '/operasional/check-out',
  getParentRoute: () => rootRouteImport,
} as any)
const OperasionalCheckInRoute = OperasionalCheckInRouteImport.update({
  id: '/operasional/check-in',
  path: '/operasional/check-in',
  getParentRoute: () => rootRouteImport,
} as any)
const OperasionalCatatanKesehatanRoute =
  OperasionalCatatanKesehatanRouteImport.update({
    id: '/operasional/catatan-kesehatan',
    path: '/operasional/catatan-kesehatan',
    getParentRoute: () => rootRouteImport,
  } as any)
const OperasionalBookingRoute = OperasionalBookingRouteImport.update({
  id: '/operasional/booking',
  path: '/operasional/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const OperasionalAktivitasHarianRoute =
  OperasionalAktivitasHarianRouteImport.update({
    id: '/operasional/aktivitas-harian',
    path: '/operasional/aktivitas-harian',
    getParentRoute: () => rootRouteImport,
  } as any)
const MasterAnakRoute = MasterAnakRouteImport.update({
  id: '/master/anak',
  path: '/master/anak',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterResourceRoute = MasterResourceRouteImport.update({
  id: '/master/$resource',
  path: '/master/$resource',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterDataResourceRoute = MasterDataResourceRouteImport.update({
  id: '/$resource',
  path: '/$resource',
  getParentRoute: () => MasterDataRoute,
} as any)
const LaporanReportRoute = LaporanReportRouteImport.update({
  id: '/laporan/$report',
  path: '/laporan/$report',
  getParentRoute: () => rootRouteImport,
} as any)
const KomunikasiPengumumanRoute = KomunikasiPengumumanRouteImport.update({
  id: '/komunikasi/pengumuman',
  path: '/komunikasi/pengumuman',
  getParentRoute: () => rootRouteImport,
} as any)
const KeuanganTagihanRoute = KeuanganTagihanRouteImport.update({
  id: '/keuangan/tagihan',
  path: '/keuangan/tagihan',
  getParentRoute: () => rootRouteImport,
} as any)
const KeuanganPembelianPaketRoute = KeuanganPembelianPaketRouteImport.update({
  id: '/keuangan/pembelian-paket',
  path: '/keuangan/pembelian-paket',
  getParentRoute: () => rootRouteImport,
} as any)
const KeuanganPembayaranRoute = KeuanganPembayaranRouteImport.update({
  id: '/keuangan/pembayaran',
  path: '/keuangan/pembayaran',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/billing': typeof BillingRoute
  '/checkin': typeof CheckinRoute
  '/children': typeof ChildrenRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/master-data': typeof MasterDataRouteWithChildren
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/user-management': typeof UserManagementRoute
  '/keuangan/pembayaran': typeof KeuanganPembayaranRoute
  '/keuangan/pembelian-paket': typeof KeuanganPembelianPaketRoute
  '/keuangan/tagihan': typeof KeuanganTagihanRoute
  '/komunikasi/pengumuman': typeof KomunikasiPengumumanRoute
  '/laporan/$report': typeof LaporanReportRoute
  '/master-data/$resource': typeof MasterDataResourceRoute
  '/master/$resource': typeof MasterResourceRoute
  '/master/anak': typeof MasterAnakRoute
  '/operasional/aktivitas-harian': typeof OperasionalAktivitasHarianRoute
  '/operasional/booking': typeof OperasionalBookingRoute
  '/operasional/catatan-kesehatan': typeof OperasionalCatatanKesehatanRoute
  '/operasional/check-in': typeof OperasionalCheckInRoute
  '/operasional/check-out': typeof OperasionalCheckOutRoute
  '/operasional/insiden': typeof OperasionalInsidenRoute
  '/pengaturan/hari-libur': typeof PengaturanHariLiburRoute
  '/pengaturan/notifikasi': typeof PengaturanNotifikasiRoute
  '/pengaturan/penomoran': typeof PengaturanPenomoranRoute
  '/pengaturan/profil': typeof PengaturanProfilRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/billing': typeof BillingRoute
  '/checkin': typeof CheckinRoute
  '/children': typeof ChildrenRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/master-data': typeof MasterDataRouteWithChildren
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/user-management': typeof UserManagementRoute
  '/keuangan/pembayaran': typeof KeuanganPembayaranRoute
  '/keuangan/pembelian-paket': typeof KeuanganPembelianPaketRoute
  '/keuangan/tagihan': typeof KeuanganTagihanRoute
  '/komunikasi/pengumuman': typeof KomunikasiPengumumanRoute
  '/laporan/$report': typeof LaporanReportRoute
  '/master-data/$resource': typeof MasterDataResourceRoute
  '/master/$resource': typeof MasterResourceRoute
  '/master/anak': typeof MasterAnakRoute
  '/operasional/aktivitas-harian': typeof OperasionalAktivitasHarianRoute
  '/operasional/booking': typeof OperasionalBookingRoute
  '/operasional/catatan-kesehatan': typeof OperasionalCatatanKesehatanRoute
  '/operasional/check-in': typeof OperasionalCheckInRoute
  '/operasional/check-out': typeof OperasionalCheckOutRoute
  '/operasional/insiden': typeof OperasionalInsidenRoute
  '/pengaturan/hari-libur': typeof PengaturanHariLiburRoute
  '/pengaturan/notifikasi': typeof PengaturanNotifikasiRoute
  '/pengaturan/penomoran': typeof PengaturanPenomoranRoute
  '/pengaturan/profil': typeof PengaturanProfilRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/billing': typeof BillingRoute
  '/checkin': typeof CheckinRoute
  '/children': typeof ChildrenRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/master-data': typeof MasterDataRouteWithChildren
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/user-management': typeof UserManagementRoute
  '/keuangan/pembayaran': typeof KeuanganPembayaranRoute
  '/keuangan/pembelian-paket': typeof KeuanganPembelianPaketRoute
  '/keuangan/tagihan': typeof KeuanganTagihanRoute
  '/komunikasi/pengumuman': typeof KomunikasiPengumumanRoute
  '/laporan/$report': typeof LaporanReportRoute
  '/master-data/$resource': typeof MasterDataResourceRoute
  '/master/$resource': typeof MasterResourceRoute
  '/master/anak': typeof MasterAnakRoute
  '/operasional/aktivitas-harian': typeof OperasionalAktivitasHarianRoute
  '/operasional/booking': typeof OperasionalBookingRoute
  '/operasional/catatan-kesehatan': typeof OperasionalCatatanKesehatanRoute
  '/operasional/check-in': typeof OperasionalCheckInRoute
  '/operasional/check-out': typeof OperasionalCheckOutRoute
  '/operasional/insiden': typeof OperasionalInsidenRoute
  '/pengaturan/hari-libur': typeof PengaturanHariLiburRoute
  '/pengaturan/notifikasi': typeof PengaturanNotifikasiRoute
  '/pengaturan/penomoran': typeof PengaturanPenomoranRoute
  '/pengaturan/profil': typeof PengaturanProfilRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activities'
    | '/billing'
    | '/checkin'
    | '/children'
    | '/dashboard'
    | '/login'
    | '/master-data'
    | '/reports'
    | '/settings'
    | '/user-management'
    | '/keuangan/pembayaran'
    | '/keuangan/pembelian-paket'
    | '/keuangan/tagihan'
    | '/komunikasi/pengumuman'
    | '/laporan/$report'
    | '/master-data/$resource'
    | '/master/$resource'
    | '/master/anak'
    | '/operasional/aktivitas-harian'
    | '/operasional/booking'
    | '/operasional/catatan-kesehatan'
    | '/operasional/check-in'
    | '/operasional/check-out'
    | '/operasional/insiden'
    | '/pengaturan/hari-libur'
    | '/pengaturan/notifikasi'
    | '/pengaturan/penomoran'
    | '/pengaturan/profil'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activities'
    | '/billing'
    | '/checkin'
    | '/children'
    | '/dashboard'
    | '/login'
    | '/master-data'
    | '/reports'
    | '/settings'
    | '/user-management'
    | '/keuangan/pembayaran'
    | '/keuangan/pembelian-paket'
    | '/keuangan/tagihan'
    | '/komunikasi/pengumuman'
    | '/laporan/$report'
    | '/master-data/$resource'
    | '/master/$resource'
    | '/master/anak'
    | '/operasional/aktivitas-harian'
    | '/operasional/booking'
    | '/operasional/catatan-kesehatan'
    | '/operasional/check-in'
    | '/operasional/check-out'
    | '/operasional/insiden'
    | '/pengaturan/hari-libur'
    | '/pengaturan/notifikasi'
    | '/pengaturan/penomoran'
    | '/pengaturan/profil'
  id:
    | '__root__'
    | '/'
    | '/activities'
    | '/billing'
    | '/checkin'
    | '/children'
    | '/dashboard'
    | '/login'
    | '/master-data'
    | '/reports'
    | '/settings'
    | '/user-management'
    | '/keuangan/pembayaran'
    | '/keuangan/pembelian-paket'
    | '/keuangan/tagihan'
    | '/komunikasi/pengumuman'
    | '/laporan/$report'
    | '/master-data/$resource'
    | '/master/$resource'
    | '/master/anak'
    | '/operasional/aktivitas-harian'
    | '/operasional/booking'
    | '/operasional/catatan-kesehatan'
    | '/operasional/check-in'
    | '/operasional/check-out'
    | '/operasional/insiden'
    | '/pengaturan/hari-libur'
    | '/pengaturan/notifikasi'
    | '/pengaturan/penomoran'
    | '/pengaturan/profil'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivitiesRoute: typeof ActivitiesRoute
  BillingRoute: typeof BillingRoute
  CheckinRoute: typeof CheckinRoute
  ChildrenRoute: typeof ChildrenRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  MasterDataRoute: typeof MasterDataRouteWithChildren
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  UserManagementRoute: typeof UserManagementRoute
  KeuanganPembayaranRoute: typeof KeuanganPembayaranRoute
  KeuanganPembelianPaketRoute: typeof KeuanganPembelianPaketRoute
  KeuanganTagihanRoute: typeof KeuanganTagihanRoute
  KomunikasiPengumumanRoute: typeof KomunikasiPengumumanRoute
  LaporanReportRoute: typeof LaporanReportRoute
  MasterResourceRoute: typeof MasterResourceRoute
  MasterAnakRoute: typeof MasterAnakRoute
  OperasionalAktivitasHarianRoute: typeof OperasionalAktivitasHarianRoute
  OperasionalBookingRoute: typeof OperasionalBookingRoute
  OperasionalCatatanKesehatanRoute: typeof OperasionalCatatanKesehatanRoute
  OperasionalCheckInRoute: typeof OperasionalCheckInRoute
  OperasionalCheckOutRoute: typeof OperasionalCheckOutRoute
  OperasionalInsidenRoute: typeof OperasionalInsidenRoute
  PengaturanHariLiburRoute: typeof PengaturanHariLiburRoute
  PengaturanNotifikasiRoute: typeof PengaturanNotifikasiRoute
  PengaturanPenomoranRoute: typeof PengaturanPenomoranRoute
  PengaturanProfilRoute: typeof PengaturanProfilRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user-management': {
      id: '/user-management'
      path: '/user-management'
      fullPath: '/user-management'
      preLoaderRoute: typeof UserManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master-data': {
      id: '/master-data'
      path: '/master-data'
      fullPath: '/master-data'
      preLoaderRoute: typeof MasterDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/children': {
      id: '/children'
      path: '/children'
      fullPath: '/children'
      preLoaderRoute: typeof ChildrenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkin': {
      id: '/checkin'
      path: '/checkin'
      fullPath: '/checkin'
      preLoaderRoute: typeof CheckinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities': {
      id: '/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof ActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pengaturan/profil': {
      id: '/pengaturan/profil'
      path: '/pengaturan/profil'
      fullPath: '/pengaturan/profil'
      preLoaderRoute: typeof PengaturanProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pengaturan/penomoran': {
      id: '/pengaturan/penomoran'
      path: '/pengaturan/penomoran'
      fullPath: '/pengaturan/penomoran'
      preLoaderRoute: typeof PengaturanPenomoranRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pengaturan/notifikasi': {
      id: '/pengaturan/notifikasi'
      path: '/pengaturan/notifikasi'
      fullPath: '/pengaturan/notifikasi'
      preLoaderRoute: typeof PengaturanNotifikasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pengaturan/hari-libur': {
      id: '/pengaturan/hari-libur'
      path: '/pengaturan/hari-libur'
      fullPath: '/pengaturan/hari-libur'
      preLoaderRoute: typeof PengaturanHariLiburRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operasional/insiden': {
      id: '/operasional/insiden'
      path: '/operasional/insiden'
      fullPath: '/operasional/insiden'
      preLoaderRoute: typeof OperasionalInsidenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operasional/check-out': {
      id: '/operasional/check-out'
      path: '/operasional/check-out'
      fullPath: '/operasional/check-out'
      preLoaderRoute: typeof OperasionalCheckOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operasional/check-in': {
      id: '/operasional/check-in'
      path: '/operasional/check-in'
      fullPath: '/operasional/check-in'
      preLoaderRoute: typeof OperasionalCheckInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operasional/catatan-kesehatan': {
      id: '/operasional/catatan-kesehatan'
      path: '/operasional/catatan-kesehatan'
      fullPath: '/operasional/catatan-kesehatan'
      preLoaderRoute: typeof OperasionalCatatanKesehatanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operasional/booking': {
      id: '/operasional/booking'
      path: '/operasional/booking'
      fullPath: '/operasional/booking'
      preLoaderRoute: typeof OperasionalBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operasional/aktivitas-harian': {
      id: '/operasional/aktivitas-harian'
      path: '/operasional/aktivitas-harian'
      fullPath: '/operasional/aktivitas-harian'
      preLoaderRoute: typeof OperasionalAktivitasHarianRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/anak': {
      id: '/master/anak'
      path: '/master/anak'
      fullPath: '/master/anak'
      preLoaderRoute: typeof MasterAnakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/$resource': {
      id: '/master/$resource'
      path: '/master/$resource'
      fullPath: '/master/$resource'
      preLoaderRoute: typeof MasterResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master-data/$resource': {
      id: '/master-data/$resource'
      path: '/$resource'
      fullPath: '/master-data/$resource'
      preLoaderRoute: typeof MasterDataResourceRouteImport
      parentRoute: typeof MasterDataRoute
    }
    '/laporan/$report': {
      id: '/laporan/$report'
      path: '/laporan/$report'
      fullPath: '/laporan/$report'
      preLoaderRoute: typeof LaporanReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/komunikasi/pengumuman': {
      id: '/komunikasi/pengumuman'
      path: '/komunikasi/pengumuman'
      fullPath: '/komunikasi/pengumuman'
      preLoaderRoute: typeof KomunikasiPengumumanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keuangan/tagihan': {
      id: '/keuangan/tagihan'
      path: '/keuangan/tagihan'
      fullPath: '/keuangan/tagihan'
      preLoaderRoute: typeof KeuanganTagihanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keuangan/pembelian-paket': {
      id: '/keuangan/pembelian-paket'
      path: '/keuangan/pembelian-paket'
      fullPath: '/keuangan/pembelian-paket'
      preLoaderRoute: typeof KeuanganPembelianPaketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keuangan/pembayaran': {
      id: '/keuangan/pembayaran'
      path: '/keuangan/pembayaran'
      fullPath: '/keuangan/pembayaran'
      preLoaderRoute: typeof KeuanganPembayaranRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MasterDataRouteChildren {
  MasterDataResourceRoute: typeof MasterDataResourceRoute
}

const MasterDataRouteChildren: MasterDataRouteChildren = {
  MasterDataResourceRoute: MasterDataResourceRoute,
}

const MasterDataRouteWithChildren = MasterDataRoute._addFileChildren(
  MasterDataRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivitiesRoute: ActivitiesRoute,
  BillingRoute: BillingRoute,
  CheckinRoute: CheckinRoute,
  ChildrenRoute: ChildrenRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  MasterDataRoute: MasterDataRouteWithChildren,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  UserManagementRoute: UserManagementRoute,
  KeuanganPembayaranRoute: KeuanganPembayaranRoute,
  KeuanganPembelianPaketRoute: KeuanganPembelianPaketRoute,
  KeuanganTagihanRoute: KeuanganTagihanRoute,
  KomunikasiPengumumanRoute: KomunikasiPengumumanRoute,
  LaporanReportRoute: LaporanReportRoute,
  MasterResourceRoute: MasterResourceRoute,
  MasterAnakRoute: MasterAnakRoute,
  OperasionalAktivitasHarianRoute: OperasionalAktivitasHarianRoute,
  OperasionalBookingRoute: OperasionalBookingRoute,
  OperasionalCatatanKesehatanRoute: OperasionalCatatanKesehatanRoute,
  OperasionalCheckInRoute: OperasionalCheckInRoute,
  OperasionalCheckOutRoute: OperasionalCheckOutRoute,
  OperasionalInsidenRoute: OperasionalInsidenRoute,
  PengaturanHariLiburRoute: PengaturanHariLiburRoute,
  PengaturanNotifikasiRoute: PengaturanNotifikasiRoute,
  PengaturanPenomoranRoute: PengaturanPenomoranRoute,
  PengaturanProfilRoute: PengaturanProfilRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
